Num1=int(input("Enter the first number: "))
Num2=int(input("Enter the second number: "))
Num3=int(input("Enter the third number: "))
PRODUCT=(Num1*Num2*Num3)
print("Your calculated product is: ",PRODUCT)